### PR TITLE
[F] Allow Empty array to be mapped

### PR DESCRIPTION
**Pull request by edon2005**

### CODE REVIEW

**Comment by sunshinejr** [comment]
Hey @edon2005, thanks for investigating it more! Are you sure that this fixes the problem with an empty array case? I was pretty sure it fails on mapping JSON to array, [here](https://github.com/sunshinejr/Moya-ModelMapper/pull/54/files#diff-30c477b5cb556531b55563e49a8cad60R43).

**Comment by edon2005** [comment]
Hej, absolutely: I verified setting fake data like: "[]" - and it is ok. if it take: "[[]]" - it fails and it is correct. if it take: "{ "test": "test"} - it fails and it is correct.

**Comment by edon2005** [comment]
Though I need reverified

**Comment by sunshinejr** [comment]
@edon2005 if you could test it again, it would be awesome. Ideally we would like to have few unit tests around it. Unfortunately there is no setup for them in the library yet and I don't really have time right now to do it. But if you have time and you would be interested in doing it, I could give you some hints on where you should start.

**Comment by edon2005** [comment]
Hej Łukasz, no problem. I would like to do it. Just let me know from where to start and what you like it should be similar tp? How do you see it? Just XCTest ? Or something more experienced? Because as I wrote I am junior. So you should be careful accepting code.

**Comment by sunshinejr** [comment]
@edon2005 No worries, you'll do fine. You can also ask any question and I'll help as much as I can.

## Test target setup
First we need to setup the test target. So normally you would just add it from Xcode project, but lately I've been using a [framework-generate](https://github.com/petester42/framework-generate). This is an awesome library that generates an `.xcodeproj` based on a [configuration file](https://github.com/sunshinejr/Moya-ModelMapper/blob/master/FrameworkSpec). Right now in this configuration file we have specified 3 targets, but we have to add another one for testing purposes.

You can look at how I configured the testing target for `SwiftyUserDefaults`, [here](https://github.com/radex/SwiftyUserDefaults/blob/master/FrameworkSpec#L9-L21). Well need to add something similar to our `FrameworkSpec` (remember to add the testing target to the array as well, [here](https://github.com/sunshinejr/Moya-ModelMapper/blob/master/FrameworkSpec#L47-L51)).

Then you need to run `framework-generate` in the root directory and it should regenerate the `Moya-ModelMapper.xcodeproj` (installation & usage should be on their GitHub page). Then just open it see if it works by building the test target).

## Tests
Then we just need to write some tests 😄 `XCTest` is fine, no need for `Quick` & `Nimble` at this stage, maybe we will transition later. For testing examples you can also see [SwiftyUserDefaults](https://github.com/radex/SwiftyUserDefaults/blob/master/Tests/SwiftyUserDefaultsTests.swift) as it uses `XCTest`. You can see the naming convention for method names and a general way of writing tests in it.

What I would like to test for now is a case for empty array JSON (`[]`), and a case for some non-empty JSON to see if we didn't break what we have right now. 

So it should be all. Let me know if something is not clear to you.

Oh, and this is time consuming, so don't worry if you don't complete it in the next few hours. Just let me know whenever there is something that blocks you or maybe when it's ready for a review 😉

**Comment by sunshinejr** [comment]
@edon2005 Hey there! I've added test target & simple test cases for the `compactMap` feature I've implemented in version 7.1.0. Are you still up for finishing this one? 😉

**Comment by edon2005** [comment]
@sunshinejr Hi, sorry for delay, unfortunately got in process of change the job :( I will be in contact on Monday. One more sorry for delay.
See soon!

**Comment by sunshinejr** [comment]
No worries @edon2005. Let me know how it went :-) 

Oh, and if you won't have time to finish this one, let me know as well, we could make an issue and someone could help you with it.

**Pull request closed without merging**
